/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BitesMixesRouteImport } from './routes/bites-mixes'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ChocolateBarsRouteImport } from './routes/chocolate-bars'
import { Route as ChocolateBoxesRouteImport } from './routes/chocolate-boxes'
import { Route as OrderDetailsRouteImport } from './routes/order-details'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PreBuiltBundlesRouteImport } from './routes/pre-built-bundles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitesMixesRoute = BitesMixesRouteImport.update({
  id: '/bites-mixes',
  path: '/bites-mixes',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChocolateBarsRoute = ChocolateBarsRouteImport.update({
  id: '/chocolate-bars',
  path: '/chocolate-bars',
  getParentRoute: () => rootRouteImport,
} as any)
const ChocolateBoxesRoute = ChocolateBoxesRouteImport.update({
  id: '/chocolate-boxes',
  path: '/chocolate-boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderDetailsRoute = OrderDetailsRouteImport.update({
  id: '/order-details',
  path: '/order-details',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PreBuiltBundlesRoute = PreBuiltBundlesRouteImport.update({
  id: '/pre-built-bundles',
  path: '/pre-built-bundles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bites-mixes': typeof BitesMixesRoute
  '/cart': typeof CartRoute
  '/chocolate-bars': typeof ChocolateBarsRoute
  '/chocolate-boxes': typeof ChocolateBoxesRoute
  '/order-details': typeof OrderDetailsRoute
  '/payment': typeof PaymentRoute
  '/pre-built-bundles': typeof PreBuiltBundlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bites-mixes': typeof BitesMixesRoute
  '/cart': typeof CartRoute
  '/chocolate-bars': typeof ChocolateBarsRoute
  '/chocolate-boxes': typeof ChocolateBoxesRoute
  '/order-details': typeof OrderDetailsRoute
  '/payment': typeof PaymentRoute
  '/pre-built-bundles': typeof PreBuiltBundlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bites-mixes': typeof BitesMixesRoute
  '/cart': typeof CartRoute
  '/chocolate-bars': typeof ChocolateBarsRoute
  '/chocolate-boxes': typeof ChocolateBoxesRoute
  '/order-details': typeof OrderDetailsRoute
  '/payment': typeof PaymentRoute
  '/pre-built-bundles': typeof PreBuiltBundlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bites-mixes'
    | '/cart'
    | '/chocolate-bars'
    | '/chocolate-boxes'
    | '/order-details'
    | '/payment'
    | '/pre-built-bundles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bites-mixes'
    | '/cart'
    | '/chocolate-bars'
    | '/chocolate-boxes'
    | '/order-details'
    | '/payment'
    | '/pre-built-bundles'
  id:
    | '__root__'
    | '/'
    | '/bites-mixes'
    | '/cart'
    | '/chocolate-bars'
    | '/chocolate-boxes'
    | '/order-details'
    | '/payment'
    | '/pre-built-bundles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitesMixesRoute: typeof BitesMixesRoute
  CartRoute: typeof CartRoute
  ChocolateBarsRoute: typeof ChocolateBarsRoute
  ChocolateBoxesRoute: typeof ChocolateBoxesRoute
  OrderDetailsRoute: typeof OrderDetailsRoute
  PaymentRoute: typeof PaymentRoute
  PreBuiltBundlesRoute: typeof PreBuiltBundlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bites-mixes': {
      id: '/bites-mixes'
      path: '/bites-mixes'
      fullPath: '/bites-mixes'
      preLoaderRoute: typeof BitesMixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chocolate-bars': {
      id: '/chocolate-bars'
      path: '/chocolate-bars'
      fullPath: '/chocolate-bars'
      preLoaderRoute: typeof ChocolateBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chocolate-boxes': {
      id: '/chocolate-boxes'
      path: '/chocolate-boxes'
      fullPath: '/chocolate-boxes'
      preLoaderRoute: typeof ChocolateBoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-details': {
      id: '/order-details'
      path: '/order-details'
      fullPath: '/order-details'
      preLoaderRoute: typeof OrderDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-built-bundles': {
      id: '/pre-built-bundles'
      path: '/pre-built-bundles'
      fullPath: '/pre-built-bundles'
      preLoaderRoute: typeof PreBuiltBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitesMixesRoute: BitesMixesRoute,
  CartRoute: CartRoute,
  ChocolateBarsRoute: ChocolateBarsRoute,
  ChocolateBoxesRoute: ChocolateBoxesRoute,
  OrderDetailsRoute: OrderDetailsRoute,
  PaymentRoute: PaymentRoute,
  PreBuiltBundlesRoute: PreBuiltBundlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
